version: '3.8'

services:
  togetup-server:
    image: togetupdev/togetupdev
    ports:
      - "9010"
    restart: always
    networks:
      - server-connection
networks:
  server-connection:
    driver: bridge


