
-- 미션
INSERT INTO mission (name, object, is_active) VALUES
                                                  ('object recognition', 'person', 1),
                                                  ('object recognition', 'bicycle', 1),
                                                  ('object recognition', 'car', 1),
                                                  ('object recognition', 'motorcycle', 1),
                                                  ('object recognition', 'bus', 1),
                                                  ('object recognition', 'train', 1),
                                                  ('object recognition', 'traffic light', 1),
                                                  ('object recognition', 'cat', 1),
                                                  ('object recognition', 'dog', 1),
                                                  ('object recognition', 'backpack', 1),
                                                  ('object recognition', 'handbag', 1),
                                                  ('object recognition', 'tie', 1),
                                                  ('object recognition', 'skateboard', 1),
                                                  ('object recognition', 'tennis racket', 1),
                                                  ('object recognition', 'bottle', 1),
                                                  ('object recognition', 'wine glass', 1),
                                                  ('object recognition', 'cup', 1),
                                                  ('object recognition', 'fork', 1),
                                                  ('object recognition', 'knife', 1),
                                                  ('object recognition', 'spoon', 1),
                                                  ('object recognition', 'bowl', 1),
                                                  ('object recognition', 'banana', 1),
                                                  ('object recognition', 'apple', 1),
                                                  ('object recognition', 'sandwich', 1),
                                                  ('object recognition', 'orange', 1),
                                                  ('object recognition', 'broccoli', 1),
                                                  ('object recognition', 'carrot', 1),
                                                  ('object recognition', 'hot dog', 1),
                                                  ('object recognition', 'pizza', 1),
                                                  ('object recognition', 'donut', 1),
                                                  ('object recognition', 'cake', 1),
                                                  ('object recognition', 'chair', 1),
                                                  ('object recognition', 'couch', 1),
                                                  ('object recognition', 'potted plant', 1),
                                                  ('object recognition', 'bed', 1),
                                                  ('object recognition', 'dining table', 1),
                                                  ('object recognition', 'toilet', 1),
                                                  ('object recognition', 'tv', 1),
                                                  ('object recognition', 'laptop', 1),
                                                  ('object recognition', 'mouse', 1),
                                                  ('object recognition', 'remotte', 1),
                                                  ('object recognition', 'keyboard', 1),
                                                  ('object recognition', 'cell phone', 1),
                                                  ('object recognition', 'microwave', 1),
                                                  ('object recognition', 'oven', 1),
                                                  ('object recognition', 'toaster', 1),
                                                  ('object recognition', 'sink', 1),
                                                  ('object recognition', 'refrigerator', 1),
                                                  ('object recognition', 'book', 1),
                                                  ('object recognition', 'clock', 1),
                                                  ('object recognition', 'vase', 1),
                                                  ('object recognition', 'hair drier', 1),
                                                  ('object recognition', 'toothbrush', 1);
